version: '3.8'

services:
  tunap_mysql:
    image: mysql:8.0.3
    environment:
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_USER: ${DB_USERNAME}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
        - ./laravel_docker/mysql-data/db:/var/lib/mysql
    ports:
        - '33063:3306'
    networks:
        - default
  tunap_php_apache:
    build:
      context: ./
      dockerfile: Dockerfile
    command: 'php artisan serve --host=0.0.0.0'
    volumes:
      - ./:/var/www/api
      - /var/www/tunap/vendor
      - ./laravel_docker/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    ports:
      - ${LARAVEL_PORT}:8000
    networks:
      - default
    depends_on:
      - tunap_postgres
      - tunap_mysql
  tunap_php_websockets:
    build:
      context: ./
      dockerfile: Dockerfile
    command: 'php artisan websockets:serve'
    volumes:
      - ./:/var/www/api
      - /var/www/api/vendor
    ports:
      - ${LARAVEL_WEBSOCKETS_PORT}:6001
    networks:
      - default
    depends_on:
      - tunap_postgres
      - tunap_mysql
      - tunap_php_apache
  tunap_php_queue:
    build:
      context: ./
      dockerfile: Dockerfile
    command: 'php artisan queue:listen'
    volumes:
      - ./:/var/www/api
      - /var/www/api/vendor
    networks:
      - default
    depends_on:
      - tunap_postgres
      - tunap_mysql
      - tunap_php_apache
